### ISSUE TITLE
File download link not working

### ISSUE THREAD

**Issue by apn99** [ataranto/CefSharp#14]
Any file download links clicked in the web browser control  opens a blank window and nothing happens. I was expecting the file link to be downloaded by the browser based on the response headers(content-type). Is this something that can be fixed in cefsharp or we have to handle the downloads in the HandleBeforeResourceLoad handler?

**Comment by ataranto** [comment]
looks like you will have to implement CefRequestHandler::GetDownloadHandler(), and return a CefDownloadHandler that can receive the download data.

**Comment by apn99** [comment]
thanks for your response. Due to time constraints and lack of my c++ skills, I found a work around, I did a process.start(downloadurl) in before popup handler which will perfom the file download after opening a link in a browser. For the time being, works for me..

**Comment by ataranto** [comment]
landed download support in ataranto/master
