### ISSUE TITLE
Support for CefSetCookie and CefSetCookiePath

### ISSUE THREAD

**Issue by davybrion** [ataranto/CefSharp#16]
Hi,

First of all, thx for the great work you've put into this project. We're evaluating using this in one of our projects and it's looking very good so far.  There's one thing missing that we need though: the ability to set a cookie from code.  libcef exposes this through the CefSetCookie and CefSetCookiePath functions (and through the CefCookieManager interface after r541) and I've gotten it to work, though my implementation is probably far from ideal due to my lack of C++ skills :)

Would you be willing to accept a pull request with these changes?

**Comment by ataranto** [comment]
Hello,

Thanks for taking a look at this. I have been out of town for a few days and haven't had time to review your changes. Please initiate a pull request and I will find some time to take a look at it this week.

--Anthony
