### ISSUE TITLE
Flash mouse movements are not proper

### ISSUE THREAD

**Issue by abhilashkk** [ataranto/CefSharp#17]
When displaying pages with flash animations, that uses user input events like mouse enter and mouse Leave, the browser control doesnot work as desired. Looks like somany mouse events are triggered (mouse enter and exit) simultaniously causing flickering on the animation. In my example, we have a button which brings in a window (help window) on mouse enter and slides out on mouse exit. But when rendered in CefSharp browser control for WPF, it always slides out continously in cycles, when I keep the mouse inside the boudaries of the button (I am not moving it, but the help window continously moves out)

**Comment by ataranto** [comment]
please reopen with a link to the problematic flash page
