### ISSUE TITLE
No sound from HTML5 <video>

### ISSUE THREAD

**Issue by rockyway** [ataranto/CefSharp#20]
I'm using the build v0.11 and cannot hear the sound from the HTML5 <video>.

**Comment by kppullin** [comment]
This is a known issue with CEF, with further details here: http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=720 .

Seems like it won't be fixed anytime soon (or ever) and instead you may need to use CEF3 or fallback to Flash.

**Comment by rockyway** [comment]
Many thanks for your answer Kevin. Now I think I will use Flash.

**Comment by ataranto** [comment]
known issue with CEF1, might work with CEF3
