### ISSUE TITLE
WebView Leaks Memory

### ISSUE THREAD

**Issue by alittletina** [ataranto/CefSharp#28]
WebView will leak memory whenever a view is removed - the HWND hook is not removed so a reference is kept and the GC will not clean up the view that has the WebView and any linked classes.

A lot of applications switch views and this becomes a big problem over time. Unfortunately I am not familiar with C++ so I cannot fix the code and make a pull request, so I request that you fix it! It is a big problem in my hobby application :(

I suggest that we automatically remove the hook or remove it when IDisposable::Dispose() is called.

Thank you!

**Comment by ataranto** [comment]
oh, thanks for the heads up. i don't switch views in my app so i've never experienced this. i'll investigate a fix when i have some time to work on CefSharp.

**Comment by ataranto** [comment]
To be clear, are you using the WinForms or WPF control when you experience this issue?

**Comment by alittletina** [comment]
Thanks for getting to this!! This occurs when using the WPF WebView.
