### ISSUE TITLE
Windows XP

### ISSUE THREAD

**Issue by bp74** [ataranto/CefSharp#29]
Hi, 

The title says pretty much everything - i need to support Windows XP for my application :(

Everything runs fine with Windows 7 (and i expect Vista too) but in Windows XP the app crashes right at the start. So my question is: Is there any way to compile CefSharp to run with Windows XP? Or am i doing something very stupid?

Thanks for your help, and thumbs up for your great work with CefSharp!

**Comment by ataranto** [comment]
CefSharp should work on XP, Vista, 7, and 8. please make sure that you have all of the necessary DLLs in place

**Comment by bp74** [comment]
I allready checked all DLLs but couldn't find the missing one - any hint would be helpful. When you look at the preprocessor compiler settings for CefSharp you see "WINVER=0x0600" which is Vista. I changed it to WindowsXP but still no luck. So my first thought was: "well ,maybe CEF itself is compiled for Vista only". I will investigate ...

**Comment by ataranto** [comment]
not sure where that WINVER comes from. i can assure you that i'm shipping a product that bundles CefSharp and works on XP.

**Comment by bp74** [comment]
Thanks for your answer. I already managed to make it work :) The only thing i have changed is the build from "Debug" to "Release". The Debug version crashes on Windows XP, the Release version runs perfectly. I don't really care why this is the case, as long as it works i'm okay with it. CefSharp is really great, and thanks for your fork - it seems to progresses faster than the code from chillitom. So i will follow your fork.

**Comment by ataranto** [comment]
Oh, thanks for letting me know. The Debug builds seem to break often depending on the CEF version, i wouldn't consider them well supported. Glad to hear release works.

chillitom started the project but isn't actively maintaining or working on CefSharp these days. I have been pushing changes to his fork only at each binary release point.
