### ISSUE TITLE
CefSharp Branches

### ISSUE THREAD

**Issue by bp74** [ataranto/CefSharp#30]
Hello, 

This is not a real issue, it's just a question. I'm pretty new the CefSharp and i really like it, i will definitely use it in my applications instead of the standard IE WebBrowser control. So i hope you can shed some light on my confusion.

The Chromium Project has differnt branches and Chrome uses some of those branches for stable releases:
The "963" branch was the stable branch for Google Chrome v17. 
The "1025" branch was the stable branch for Google Chrome v18. 
The "1084" branch was the stable branch for Google Chrome v19. 
The "1132" branch is the stable branch for Google Chrome v20.
The "1180" branch will be the stable branch for Chrome v21.

The CEF1 project offers downloads for the"1025" and the older "963" branch. There are no downloads for "1084" or "1132" and the "1180" branch is CEF3 only. 

The chillitom/CefSharp github repository includes branch "1092" - it looks to me that this was a branch somewhere between Google Chrome v19 and V20. But is this a stable build?

The ataranto/CefSharp github repository includes branch "1180" - which is great but this one is not yet stable. In my case it crashes on some of my sites like www.funworld.com.

Okay finally my question: If i want to build an application for production use, What is the right branch to follow? Currently none of the both major CefSharp repositories offer a stable branch. Do i have to create my own fork for building something like a "1132" branch for CefSharp?

You see i'm a little bit confused :) You are doing a great job, thanks for all your effort!

**Comment by bp74** [comment]
Let me add one thing. I think the "1180" branch will be stable soon, so maybe it would be a good idea to create a "stable" branch in the "ataranto/CefSharp" repository. The branch will offer a stable release as long as "1180" is the current stable version of Chromium. This would be awesome!

**Comment by ataranto** [comment]
Generally, CefSharp has tracked CEF trunk and CefSharp releases were made rather arbitrarily based on added features or stability.

However, that's probably not a great long term solution.

Also, it looks like CEF's 1180 branch is only going to support the cef3 architecture, not the cef1 architecture that CefSharp currently binds. Preliminary work on binding CEF3 can be found in my cef3 branch: https://github.com/ataranto/CefSharp/tree/cef3

I am going to spend some time this afternoon making a binary release for the 1084/v19 branch.

**Comment by bp74** [comment]
Okay i understand, i thought you had the 1180 branch because "libcef.dll" says it is version 1.1180.728.0. I saw that CEF had a 1084 branch too, which would be great if you could use it for a stable CefSharp release. I just tested your new commits but i see the same crash with our own website (www.funworld.com). 
Now i'm in troubles and it will be difficult to convince my boss to use CEF for our project when our own homepage crashes the browser :( Thanks anyway for your effort so far!
