### ISSUE TITLE
CefSharp WPF control crashes when interacting with HTML drop down lists (HTML select tag)

### ISSUE THREAD

**Issue by kishorereddik** [ataranto/CefSharp#41]
CefSharp WPF control crashes when interacting with HTML drop down lists (HTML select tag)

The issue can be re-producible with CefSharp.WinForms.Example.exe

Steps to re-produce:
1. Launch CefSharp.WinForms.Example.exe
2. Browse the attached 'dropdown-lists.html' file
         OR
   you can browse any website that has form with drop down select list, for example
   http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
   1. Try repeatedly click on the drop down menu to display the popup
3. You can also notice artifacts while rendering the popup
4. It crashes with the following exception:
   
   System.AccessViolationException was unhandled
     Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
     Source=CefSharp.Wpf
     StackTrace:
          at memcpy(Void\* , Void\* , UInt32 )
          at CefSharp.Wpf.WebView.SetBuffer(Int32\* currentWidth, Int32\* currentHeight, Int32 width, Int32 height, Void*\* fileMappingHandle, Void*\* backBufferHandle, InteropBitmap\* ibitmap, ActionHandler paintDelegate, Void\* buffer)
          at CefSharp.Wpf.WebView.SetPopupBuffer(Int32 width, Int32 height, Void\* buffer)
          at CefSharp.RenderClientAdapter.OnPaint(RenderClientAdapter\* , CefRefPtr<CefBrowser>\* browser, cef_paint_element_type_t type, vector<CefRect\,std::allocator<CefRect> >\* dirtyRects, Void\* buffer)

Note: I am not experiencing this problem with CefSharp.WinForms control. It is working fine with the WinForms control.
## 'dropdown-lists.html

<!DOCTYPE html>
<html>
<head></head>
<body>

<table>
    <tbody>
        <tr>
            <td class="right"><label for="Font_FontFamily">Font:</label></td>
            <td>&nbsp;</td>
            <td colspan="3">
                <select name="Font.FontFamily" id="Font_FontFamily">
                    <option value="Arial" selected="selected">Arial</option>
                    <option value="Batang">Batang</option>
                    <option value="BatangChe">BatangChe</option>
                    <option value="Gungsuh">Gungsuh</option>
                    <option value="GungsuhChe">GungsuhChe</option>
                    <option value="Courier New">Courier New</option>
                    <option value="DaunPenh">DaunPenh</option>
                    <option value="DokChampa">DokChampa</option>
                    <option value="Estrangelo Edessa">Estrangelo Edessa</option>
                    <option value="Euphemia">Euphemia</option>
                    <option value="Gautami">Gautami</option>
                    <option value="Gulim">Gulim</option>
                    <option value="GulimChe">GulimChe</option>
                    <option value="Dotum">Dotum</option>
                    <option value="DotumChe">DotumChe</option>
                    <option value="Impact">Impact</option>
                    <option value="Iskoola Pota">Iskoola Pota</option>
                    <option value="Kalinga">Kalinga</option>
                    <option value="Kartika">Kartika</option>
                    <option value="Latha">Latha</option>
                    <option value="Lucida Console">Lucida Console</option>
                    <option value="Malgun Gothic">Malgun Gothic</option>
                    <option value="Mangal">Mangal</option>
                    <option value="Microsoft Himalaya">Microsoft Himalaya</option>
                    <option value="Microsoft JhengHei">Microsoft JhengHei</option>
                    <option value="Microsoft YaHei">Microsoft YaHei</option>
                    <option value="MingLiU">MingLiU</option>
                    <option value="PMingLiU">PMingLiU</option>
                    <option value="MingLiU_HKSCS">MingLiU_HKSCS</option>
                    <option value="MingLiU-ExtB">MingLiU-ExtB</option>
                    <option value="PMingLiU-ExtB">PMingLiU-ExtB</option>
                    <option value="MingLiU_HKSCS-ExtB">MingLiU_HKSCS-ExtB</option>
                    <option value="Mongolian Baiti">Mongolian Baiti</option>
                    <option value="MS Gothic">MS Gothic</option>
                    <option value="MS PGothic">MS PGothic</option>
                    <option value="MS UI Gothic">MS UI Gothic</option>
                    <option value="MS Mincho">MS Mincho</option>
                    <option value="MS PMincho">MS PMincho</option>
                    <option value="MV Boli">MV Boli</option>
                    <option value="Nyala">Nyala</option>
                    <option value="Plantagenet Cherokee">Plantagenet Cherokee</option>
                    <option value="Raavi">Raavi</option>
                    <option value="Segoe Script">Segoe Script</option>
                    <option value="Segoe UI">Segoe UI</option>
                    <option value="Shruti">Shruti</option>
                    <option value="SimSun">SimSun</option>
                    <option value="NSimSun">NSimSun</option>
                    <option value="SimSun-ExtB">SimSun-ExtB</option>
                    <option value="Sylfaen">Sylfaen</option>
                    <option value="Times New Roman">Times New Roman</option>
                    <option value="Tunga">Tunga</option>
                    <option value="Vrinda">Vrinda</option>
                    <option value="Microsoft Yi Baiti">Microsoft Yi Baiti</option>
                    <option value="Tahoma">Tahoma</option>
                    <option value="Microsoft Sans Serif">Microsoft Sans Serif</option>
                    <option value="Angsana New">Angsana New</option>
                    <option value="Cordia New">Cordia New</option>
                    <option value="Gisha">Gisha</option>
                    <option value="Leelawadee">Leelawadee</option>
                    <option value="Microsoft Uighur">Microsoft Uighur</option>
                    <option value="MoolBoran">MoolBoran</option>
                    <option value="Symbol">Symbol</option>
                    <option value="Wingdings">Wingdings</option>
                    <option value="Andalus">Andalus</option>
                    <option value="Arabic Typesetting">Arabic Typesetting</option>
                    <option value="Simplified Arabic">Simplified Arabic</option>
                    <option value="Simplified Arabic Fixed">Simplified Arabic Fixed</option>
                    <option value="Traditional Arabic">Traditional Arabic</option>
                    <option value="Aharoni">Aharoni</option>
                    <option value="David">David</option>
                    <option value="FrankRuehl">FrankRuehl</option>
                    <option value="Levenim MT">Levenim MT</option>
                    <option value="Miriam">Miriam</option>
                    <option value="Miriam Fixed">Miriam Fixed</option>
                    <option value="Narkisim">Narkisim</option>
                    <option value="Rod">Rod</option>
                    <option value="FangSong">FangSong</option>
                    <option value="SimHei">SimHei</option>
                    <option value="KaiTi">KaiTi</option>
                    <option value="AngsanaUPC">AngsanaUPC</option>
                    <option value="Browallia New">Browallia New</option>
                    <option value="BrowalliaUPC">BrowalliaUPC</option>
                    <option value="CordiaUPC">CordiaUPC</option>
                    <option value="DilleniaUPC">DilleniaUPC</option>
                    <option value="EucrosiaUPC">EucrosiaUPC</option>
                    <option value="FreesiaUPC">FreesiaUPC</option>
                    <option value="IrisUPC">IrisUPC</option>
                    <option value="JasmineUPC">JasmineUPC</option>
                    <option value="KodchiangUPC">KodchiangUPC</option>
                    <option value="LilyUPC">LilyUPC</option>
                    <option value="DFKai-SB">DFKai-SB</option>
                    <option value="Lucida Sans Unicode">Lucida Sans Unicode</option>
                    <option value="Comic Sans MS">Comic Sans MS</option>
                    <option value="Franklin Gothic">Franklin Gothic</option>
                    <option value="Georgia">Georgia</option>
                    <option value="Palatino Linotype">Palatino Linotype</option>
                    <option value="Segoe Print">Segoe Print</option>
                    <option value="Trebuchet MS">Trebuchet MS</option>
                    <option value="Verdana">Verdana</option>
                    <option value="Webdings">Webdings</option>
                    <option value="Haettenschweiler">Haettenschweiler</option>
                    <option value="Book Antiqua">Book Antiqua</option>
                    <option value="Century Gothic">Century Gothic</option>
                    <option value="Garamond">Garamond</option>
                    <option value="Monotype Corsiva">Monotype Corsiva</option>
                    <option value="Agency FB">Agency FB</option>
                    <option value="Arial Rounded MT">Arial Rounded MT</option>
                    <option value="Blackadder ITC">Blackadder ITC</option>
                    <option value="Bodoni MT">Bodoni MT</option>
                    <option value="Bookman Old Style">Bookman Old Style</option>
                    <option value="Bradley Hand ITC">Bradley Hand ITC</option>
                    <option value="Calisto MT">Calisto MT</option>
                    <option value="Castellar">Castellar</option>
                    <option value="Century Schoolbook">Century Schoolbook</option>
                    <option value="Copperplate Gothic">Copperplate Gothic</option>
                    <option value="Curlz MT">Curlz MT</option>
                    <option value="Edwardian Script ITC">Edwardian Script ITC</option>
                    <option value="Elephant">Elephant</option>
                    <option value="Engravers MT">Engravers MT</option>
                    <option value="Eras ITC">Eras ITC</option>
                    <option value="Felix Titling">Felix Titling</option>
                    <option value="Forte">Forte</option>
                    <option value="Franklin Gothic Book">Franklin Gothic Book</option>
                    <option value="French Script MT">French Script MT</option>
                    <option value="Gigi">Gigi</option>
                    <option value="Gill Sans MT">Gill Sans MT</option>
                    <option value="Gill Sans">Gill Sans</option>
                    <option value="Gloucester MT">Gloucester MT</option>
                    <option value="Goudy Old Style">Goudy Old Style</option>
                    <option value="Goudy Stout">Goudy Stout</option>
                    <option value="Imprint MT Shadow">Imprint MT Shadow</option>
                    <option value="Lucida Sans">Lucida Sans</option>
                    <option value="Lucida Sans Typewriter">Lucida Sans Typewriter</option>
                    <option value="Maiandra GD">Maiandra GD</option>
                    <option value="OCR A">OCR A</option>
                    <option value="Palace Script MT">Palace Script MT</option>
                    <option value="Papyrus">Papyrus</option>
                    <option value="Perpetua">Perpetua</option>
                    <option value="Perpetua Titling MT">Perpetua Titling MT</option>
                    <option value="Pristina">Pristina</option>
                    <option value="Rage">Rage</option>
                    <option value="Rockwell">Rockwell</option>
                    <option value="Script MT">Script MT</option>
                    <option value="Tw Cen MT">Tw Cen MT</option>
                    <option value="Algerian">Algerian</option>
                    <option value="Baskerville Old Face">Baskerville Old Face</option>
                    <option value="Bauhaus 93">Bauhaus 93</option>
                    <option value="Bell MT">Bell MT</option>
                    <option value="Berlin Sans FB">Berlin Sans FB</option>
                    <option value="Bernard MT">Bernard MT</option>
                    <option value="Bodoni MT Poster">Bodoni MT Poster</option>
                    <option value="Britannic">Britannic</option>
                    <option value="Broadway">Broadway</option>
                    <option value="Brush Script MT">Brush Script MT</option>
                    <option value="Californian FB">Californian FB</option>
                    <option value="Centaur">Centaur</option>
                    <option value="Chiller">Chiller</option>
                    <option value="Colonna MT">Colonna MT</option>
                    <option value="Cooper">Cooper</option>
                    <option value="Footlight MT">Footlight MT</option>
                    <option value="Freestyle Script">Freestyle Script</option>
                    <option value="Harlow Solid">Harlow Solid</option>
                    <option value="Harrington">Harrington</option>
                    <option value="High Tower Text">High Tower Text</option>
                    <option value="Jokerman">Jokerman</option>
                    <option value="Juice ITC">Juice ITC</option>
                    <option value="Kristen ITC">Kristen ITC</option>
                    <option value="Kunstler Script">Kunstler Script</option>
                    <option value="Lucida Bright">Lucida Bright</option>
                    <option value="Lucida Calligraphy">Lucida Calligraphy</option>
                    <option value="Lucida Fax">Lucida Fax</option>
                    <option value="Lucida Handwriting">Lucida Handwriting</option>
                    <option value="Magneto">Magneto</option>
                    <option value="Matura MT Script Capitals">Matura MT Script Capitals</option>
                    <option value="Mistral">Mistral</option>
                    <option value="Modern No. 20">Modern No. 20</option>
                    <option value="Niagara Engraved">Niagara Engraved</option>
                    <option value="Niagara Solid">Niagara Solid</option>
                    <option value="Old English Text MT">Old English Text MT</option>
                    <option value="Onyx">Onyx</option>
                    <option value="Parchment">Parchment</option>
                    <option value="Playbill">Playbill</option>
                    <option value="Poor Richard">Poor Richard</option>
                    <option value="Ravie">Ravie</option>
                    <option value="Informal Roman">Informal Roman</option>
                    <option value="Showcard Gothic">Showcard Gothic</option>
                    <option value="Snap ITC">Snap ITC</option>
                    <option value="Stencil">Stencil</option>
                    <option value="Tempus Sans ITC">Tempus Sans ITC</option>
                    <option value="Viner Hand ITC">Viner Hand ITC</option>
                    <option value="Vivaldi">Vivaldi</option>
                    <option value="Vladimir Script">Vladimir Script</option>
                    <option value="Wide Latin">Wide Latin</option>
                    <option value="Century">Century</option>
                    <option value="Wingdings 2">Wingdings 2</option>
                    <option value="Wingdings 3">Wingdings 3</option>
                    <option value="Arial Unicode MS">Arial Unicode MS</option>
                    <option value="Nina">Nina</option>
                    <option value="Segoe">Segoe</option>
                    <option value="Meiryo UI">Meiryo UI</option>
                    <option value="Meiryo">Meiryo</option>
                    <option value="Eenadu">Eenadu</option>
                    <option value="Shree-0908W">Shree-0908W</option>
                    <option value="ZDingbats">ZDingbats</option>
                    <option value="Buxton Sketch">Buxton Sketch</option>
                    <option value="Segoe Marker">Segoe Marker</option>
                    <option value="SketchFlow Print">SketchFlow Print</option>
                    <option value="MT Extra">MT Extra</option>
                    <option value="Calibri">Calibri</option>
                    <option value="Cambria">Cambria</option>
                    <option value="Cambria Math">Cambria Math</option>
                    <option value="Candara">Candara</option>
                    <option value="Consolas">Consolas</option>
                    <option value="Constantia">Constantia</option>
                    <option value="Corbel">Corbel</option>
                    <option value="MS Outlook">MS Outlook</option>
                    <option value="Gabriola">Gabriola</option>
                    <option value="Bookshelf Symbol 7">Bookshelf Symbol 7</option>
                    <option value="MS Reference Sans Serif">MS Reference Sans Serif</option>
                    <option value="MS Reference Specialty">MS Reference Specialty</option>
                    <option value="Marlett">Marlett</option>
                    <option value="Global User Interface">Global User Interface</option>
                    <option value="Global Monospace">Global Monospace</option>
                    <option value="Global Sans Serif">Global Sans Serif</option>
                    <option value="Global Serif">Global Serif</option>
                </select>
            </td>
            <td>
                <select name="Font.FontSize" id="Font_FontSize">
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11" selected="selected">11</option>
                    <option value="12">12</option>
                    <option value="14">14</option>
                    <option value="16">16</option>
                    <option value="18">18</option>
                    <option value="20">20</option>
                    <option value="22">22</option>
                    <option value="24">24</option>
                    <option value="26">26</option>
                    <option value="28">28</option>
                    <option value="36">36</option>
                    <option value="48">48</option>
                    <option value="72">72</option>
                </select>
            </td>
        </tr>
    </tbody>
</table>

</body>  
</html>

**Comment by ataranto** [comment]
should be fixed by abaaa9784156af0269ea3f9f5cbd4114a3a21f86
