### ISSUE TITLE
Cef can‘t complied for X64

### ISSUE THREAD

**Issue by sohard815** [ataranto/CefSharp#46]
when compile the CefSharp.dll for X64,it will show error about libcef_dll_wrapper.lib.it only can compiled with X86 ,how to solve it?thank u

**Comment by ataranto** [comment]
"Neither Chromium nor V8 has a 64-bit version on the Windows platform right now."

https://sites.google.com/a/chromium.org/dev/developers/design-documents/64-bit-support

**Comment by sohard815** [comment]
when will it can be compiled for X64，it is no way to solve the error "libcef_dll_wrapper.lib(v8value_ctocpp.obj) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'" right now ,right?

**Comment by ataranto** [comment]
CEF or CefSharp definitely won't support x64 builds until Chromium itself does.

**Comment by sohard815** [comment]
ok,thank u !
now my project need to be compiled for X64,is there any way to ref Cef?
thank u very much?
